# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1pjOw72ru8wTAzLXoplF-5L9EW4FYn5
"""

pip install streamlit yfinance pandas plotly twstock

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime, timedelta

st.set_page_config(page_title="我的台股分析", page_icon="📈", layout="wide")
st.title("📈 我的台股投資分析")

# 側邊欄輸入股票代碼
st.sidebar.header("🔍 查詢股票")
ticker_input = st.sidebar.text_input("輸入台股代碼（例如：2330）", value="2330")
days = st.sidebar.slider("查詢天數", 30, 365, 180)

ticker = ticker_input + ".TW"
end = datetime.today()
start = end - timedelta(days=days)

@st.cache_data(ttl=3600)
def get_data(ticker, start, end):
    df = yf.download(ticker, start=start, end=end)
    # 若欄位是 MultiIndex，壓平成單層
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df

df = get_data(ticker, start, end)

if df.empty:
    st.error("找不到此股票，請確認代碼是否正確")
else:
    # ── 取出純數值，避免 Series format 錯誤 ──────────────────────
    last_price  = float(df['Close'].iloc[-1])
    prev_price  = float(df['Close'].iloc[-2])
    last_volume = float(df['Volume'].iloc[-1])

    # 基本資訊
    info = yf.Ticker(ticker).info
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("公司名稱", info.get('longName', ticker_input))
    col2.metric("目前股價", f"NT${last_price:.1f}")

    change     = last_price - prev_price
    change_pct = change / prev_price * 100
    col3.metric("漲跌", f"{change:+.1f}", f"{change_pct:+.2f}%")
    col4.metric("成交量", f"{int(last_volume / 1000)}張")

    # K 線圖
    st.subheader("📊 K線圖")
    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],
        name="K線"
    ))

    # 均線
    df['MA20'] = df['Close'].rolling(20).mean()
    df['MA60'] = df['Close'].rolling(60).mean()
    fig.add_trace(go.Scatter(x=df.index, y=df['MA20'], name="20日均線", line=dict(color='orange')))
    fig.add_trace(go.Scatter(x=df.index, y=df['MA60'], name="60日均線", line=dict(color='blue')))
    fig.update_layout(height=500, xaxis_rangeslider_visible=False)
    st.plotly_chart(fig, use_container_width=True)

    # 技術指標（簡易買賣點）
    st.subheader("🎯 簡易買賣點判斷")
    last_close  = float(df['Close'].iloc[-1])
    prev_close  = float(df['Close'].iloc[-2])
    ma20        = float(df['MA20'].iloc[-1])
    ma60        = float(df['MA60'].iloc[-1])
    prev_ma20   = float(df['MA20'].iloc[-2])

    signals = []
    if last_close > ma20 and prev_close <= prev_ma20:
        signals.append(("✅ 黃金交叉", "股價突破20日均線，短線偏多", "買進參考"))
    if last_close < ma20 and prev_close >= prev_ma20:
        signals.append(("⚠️ 死亡交叉", "股價跌破20日均線，短線偏空", "賣出參考"))
    if last_close > ma20 and last_close > ma60:
        signals.append(("📈 多頭排列", "股價在雙均線之上，趨勢向好", "持有"))
    if last_close < ma20 and last_close < ma60:
        signals.append(("📉 空頭排列", "股價在雙均線之下，趨勢偏弱", "觀望"))

    if signals:
        for icon, desc, action in signals:
            st.info(f"{icon}　{desc}　→　**{action}**")
    else:
        st.info("目前無明確信號，持續觀察中")

    # 估值參考
    st.subheader("💰 估值參考")
    pe = info.get('trailingPE')
    pb = info.get('priceToBook')
    dy = info.get('dividendYield')

    c1, c2, c3 = st.columns(3)
    c1.metric("本益比 (PE)",   f"{pe:.1f}"      if pe else "無資料")
    c2.metric("股價淨值比 (PB)", f"{pb:.2f}"    if pb else "無資料")
    c3.metric("股息殖利率",    f"{dy*100:.2f}%" if dy else "無資料")

    # 近期資料表
    st.subheader("📋 近10日資料")
    display_df = df[['Open', 'High', 'Low', 'Close', 'Volume']].tail(10).sort_index(ascending=False).copy()
    display_df.columns = ['開盤', '最高', '最低', '收盤', '成交量']
    # 成交量單獨格式化，其餘顯示小數一位
    st.dataframe(
        display_df.style.format({
            '開盤': '{:.1f}',
            '最高': '{:.1f}',
            '最低': '{:.1f}',
            '收盤': '{:.1f}',
            '成交量': '{:,.0f}',
        }),
        use_container_width=True
    )